DROP TABLE IF EXISTS Users;
CREATE TABLE Users
(
  Email CHAR(21) NOT NULL,
  Password VARCHAR(50) NOT NULL,
  PRIMARY KEY (Email)
);

DROP TABLE IF EXISTS Event;
CREATE TABLE Event
(
  EventName INT NOT NULL,
  Date INT NOT NULL,
  EventID INT NOT NULL,
  PRIMARY KEY (EventID)
);

DROP TABLE IF EXISTS Tickets;
CREATE TABLE Tickets
(
  TicketID INT NOT NULL,
  isForSale CHAR(1) NOT NULL,
  Email CHAR(21) NOT NULL,
  EventID INT NOT NULL,
  PRIMARY KEY (TicketID),
  FOREIGN KEY (Email) REFERENCES Users(Email),
  FOREIGN KEY (EventID) REFERENCES Event(EventID)
);

DROP TABLE IF EXISTS Asks;
CREATE TABLE Asks
(
  Price INT NOT NULL,
  TicketID INT NOT NULL,
  Email CHAR(21) NOT NULL,
  FOREIGN KEY (TicketID) REFERENCES Tickets(TicketID),
  FOREIGN KEY (Email) REFERENCES Users(Email)
);

DROP TABLE IF EXISTS Bids;
CREATE TABLE Bids
(
  Price INT NOT NULL,
  Email CHAR(21) NOT NULL,
  TicketID INT NOT NULL,
  FOREIGN KEY (Email) REFERENCES Users(Email),
  FOREIGN KEY (TicketID) REFERENCES Tickets(TicketID)
);